config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks, only: [:index, :show] do  
    resources :user_tasks, only: [:create, :destroy]
  end 

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :users_tasks
    has_many :users, through: :user_tasks
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usertask.rb
class Usertask < ApplicationRecord
    belongs_to :user 
    belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!, except: :index
  
    def index
      @tasks = Task.all
    end
  
    def show
      @task = Task.find(params[:id])
      @ranking = @task.users.limit(5).sort_by(&:created_at)
      @users = @task.users
    end
  
  end

  

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
    def create
      UserTask.create(user: current_user, task_id: params[:task_id])
      redirect_back(fallback_location: root_path)
    end
  
    def destroy
      UserTask.find_by(user: params[:id], task_id: params[:task_id]).destroy
      redirect_back(fallback_location: root_path)
    end
  
  end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="row">
<% @tasks.each do |task| %>
  <div class="col-md-4">
  <div class="card" style="text-align: center; margin-top: 20px">
    <img class="card-img-top" src="<%= task.photo %>" >
    <div class="card-body">
      <h5 class="card-title"><%= task.name %></h5>
      <%= link_to 'Detalles', task, class: 'btn btn-light' %>
      
    </div>
  </div>
  </div>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="row justify-content-center">
  <div class="card" style="text-align: center;">
    <img class="card-img-top" src="<%= @task.photo %>" >
    <div class="card-body">
      <h5 class="card-title"><%= @task.name %></h5>
        <% if current_user.tasks.where(id: @task.id).present? %>
          <%= link_to 'Hecha', task_user_task_path(@task.id, id: current_user), method: :delete, class: 'btn btn-success' %>
        <% else %>
          <%= link_to 'Aún por hacer', task_user_tasks_path(@task.id), method: :postm, class: 'btn btn-warning' %>
        <% end %>
    </div>
  </div>
</div>
<br>

<% if @ranking.present? %>
  <h3 style="text-align: center">Primeros en completarla:</h3>
  <div class="row">
    <% @ranking.each do |user| %>
      <div class="col-md-4">  
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= user.photo %>">
          <div class="card-body">
            <h5 class="card-title"><%= user.email %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <% if @users.count > 5 %>
    <ul>
      <h4>La ha completado: </h4>
      <% @users.each do |user| %>
        <li><%= user.email %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>